include:
  - template: Security/Secret-Detection.gitlab-ci.yml

stages:
  - test

cfn-lint:
  image: python:latest
  stage: test
  script:
  - python --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install cfn-lint
  - pip freeze    
  - cfn-lint -I infrastructure/cfn.yaml

secret_detection:
  stage: test
  variables:
    CI_DEBUG_TRACE: "true"
