include:
  - template: Security/Secret-Detection.gitlab-ci.yml

cfn-lint:
  image: python:latest
  stage: test
  before_script:
    - python --version  # For debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install cfn-lint
    - pip freeze    
  script:
    - cfn-lint -I infrastructure/cfn.yaml

cfn-nag:
  image: stelligent/cfn_nag
  stage: test
  script:
    - cfn_nag_scan --input-path infrastructure/cfn.yaml

secret_detection:
  stage: test
  variables:
    CI_DEBUG_TRACE: "true"

# build-artifact:
#   stage: build
#   script:
#   - zip -r aws-alphafold.zip . -x .\*/|*

push-to-s3:
  stage: deploy
  variables:
    AWS_CREDS_TARGET_ROLE: arn:aws:iam::111918798052:role/AWS-Alphafold-GitLab-CI-Role
    AWS_DEFAULT_REGION: us-east-1
  script:
    - aws s3 ls