version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - zip -r aws-alphafold.zip
  post-build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - aws-alphafold.zip
